export enum BodyPart {
  BACK = "Back",
  CARDIO = "Cardio",
  CHEST = "Chest",
  LOWER_ARMS = "Lower arms",
  LOWER_LEGS = "Lower legs",
  NECK = "Neck",
  SHOULDERS = "Shoulders",
  UPPER_ARMS = "Upper arms",
  UPPER_LEGS = "Upper legs",
  WAIST = "Waist",
}

export enum Muscle {
  ABDUCTORS = "Abductors",
  ABS = "Abs",
  ADDUCTORS = "Adductors",
  BICEPS = "Biceps",
  CALVES = "Calves",
  CARDIOVASCULAR_SYSTEM = "Cardiovascular system",
  DELTS = "Delts",
  FOREARMS = "Forearms",
  GLUTES = "Glutes",
  HAMSTRINGS = "Hamstrings",
  LATS = "Lats",
  LEVATOR_SCAPULA = "Levator scapula",
  PECTORALS = "Pectorals",
  QUADS = "Quads",
  SERRATUS_ANTERIOR = "Serratus anterior",
  SPINE = "Spine",
  TRAPS = "Traps",
  TRICEPS = "Triceps",
  UPPER_BACK = "Upper back",
}

export enum Equipment {
  ASSISTED = "Assisted",
  BAND = "Band",
  BARBELL = "Barbell",
  BODY_WEIGHT = "Body weight",
  BOSU_BALL = "Bosu ball",
  CABLE = "Cable",
  DUMBBELL = "Dumbbell",
  ELLIPTICAL_MACHINE = "Elliptical machine",
  EZ_BARBELL = "EZ barbell",
  HAMMER = "Hammer",
  KETTLEBELL = "Kettlebell",
  LEVERAGE_MACHINE = "Leverage machine",
  MEDICINE_BALL = "Medicine ball",
  OLYMPIC_BARBELL = "Olympic barbell",
  RESISTANCE_BAND = "Resistance band",
  ROLLER = "Roller",
  ROPE = "Rope",
  SKIERG_MACHINE = "Skierg machine",
  SLED_MACHINE = "Sled machine",
  SMITH_MACHINE = "Smith machine",
  STABILITY_BALL = "Stability ball",
  STATIONARY_BIKE = "Stationary bike",
  STEPMILL_MACHINE = "Stepmill machine",
  TIRE = "Tire",
  TRAP_BAR = "Trap bar",
  UPPER_BODY_ERGOMETER = "Upper body ergometer",
  WEIGHTED = "Weighted",
  WHEEL_ROLLER = "Wheel roller",
}
